menu:
- {name: 'papers', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}


social:
- {icon: 'github', link: 'https://github.com/AlisonZ'}
- {icon: 'instagram', link: 'https://www.instagram.com/theoriginalakz/'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/alisonzerbe'}

contacts:
- {name: 'Alison Zerbe', title: 'Student', department: 'CLMS', institution: 'University of Washington', email: 'zerbea@uw.edu', image: 'assets/img/phones.jpg'}

experience:
- {institution: 'Indeed', dates: '2017 - present', role: "Software Engineer"}
- {institution: 'UC Berkeley', dates: '2013 - 2015', role: "Lingustics MA"}
